### ISSUE TITLE
Duplicate ElementTagNameMap when using inside other Stencil project

### ISSUE THREAD

**Issue by valadas** [nvisionative/nvQuickComponents#15]
There is a bug in order versions of Stencil that give this result sometimes when using a Stencil component project inside another Stencil project:

![image](https://user-images.githubusercontent.com/6371568/71760650-e296f880-2e8e-11ea-93f9-3db5e47fb2ce.png)

After reading to old issues here and there it looks like this is resolved by upgrading the Stencil version on the imported project.

I will try to submit a PR for this tomorrow...

**Comment by david-poindexter** [comment]
Closing per #16
