### ISSUE TITLE
There is a lot of Commit Noise with the Dist Folder

### ISSUE THREAD

**Issue by ahoefling** [nvisionative/nvQuickComponents#3]
There is a lot of commit noise since the dist changes quite a bit with each build of stenciljs. In my own project I got around this by not including the dist folder in the repo and only use it when I package up the project for publishing to our local npm feed. We could try this or maybe we could setup a dev branch and master branch where the dev branch does not include the dist.

**Comment by ahoefling** [comment]
The challenge here is how do we want people to contribute and what do we want people to first see when they come to the repo.

I am a fan of someone being able to clone a repo and go to the examples and just see stuff working. So I would say master should be the default branch. If we do that though then contributing becomes confusing, what branch do you contribute to? If we choose to have master be the default branch and we want PRs to come through development then we need a VERY clear contributing guide and maybe an extra note on the readme that PRs should be sent against the Dev branch

**Comment by nvisionative** [comment]
@ahoefling I was thinking the same thing.  At this time, unless you oppose, I am good with **master** being the default branch on the repo and we will start using **development** for PRs.  We can also work on a **CONTRIBUTING.md**.  I'll create a few issues for each of these.

**Comment by nvisionative** [comment]
See #11 and #12

**Comment by valadas** [comment]
IMO, gitflow makes a lot of sense, master is what is in production and everything else needs to merge into development :) I have done quite a few stencil projects now and never commit the dist folder. I use a npm publish task that builds and publishes in CI only. Ping me up if you want to look at it or work together on a PR for this.

**Comment by david-poindexter** [comment]
@valadas yes, let's chat when I get back from vacation.  I am going to go ahead and close this issue since it was originally about the `dist` folder (which is now not committed).
